[package]
name = "daq-core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
rsntp = "3.0"
lazy_static = "1.4"
log = "0.4"
